/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.internals;

import java.awt.image.BufferedImage;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import org.krysalis.barcode4j.impl.code128.Code128Bean;
import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;

/**
 *
 * @author vishv
 */
public class PnlCardBack extends javax.swing.JPanel {

    /**
     * Creates new form PnlCardBack
     * @param name
     * @param studentId
     */
    public PnlCardBack(String name, String studentId) {
        initComponents();
        
        lblBarcode.setIcon(new ImageIcon(generateBarcodeImage(studentId)));
        lblName.setText(name);
        
        lblDate.setText("Issued Date: " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
    }
    
    public BufferedImage generateBarcodeImage(String text) {
        Code128Bean barcodeGenerator = new Code128Bean();
        final int dpi = 160;

        // Configure the barcode generator
        barcodeGenerator.setModuleWidth(0.3); // Set width of barcode bars
        barcodeGenerator.doQuietZone(false);

        // Set up the image canvas
        BufferedImage barcodeImage = null;
        try (OutputStream out = new java.io.ByteArrayOutputStream()) {
            BitmapCanvasProvider canvas = new BitmapCanvasProvider(
                    out, "image/x-png", dpi, BufferedImage.TYPE_BYTE_BINARY, false, 0);

            // Generate the barcode
            barcodeGenerator.generateBarcode(canvas, text);

            // Complete the image and return
            canvas.finish();
            barcodeImage = canvas.getBufferedImage();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return barcodeImage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(484, 306));
        setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/card_back_header.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 66));
        add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Wishva Chandrasekara");

        lblBarcode.setBackground(new java.awt.Color(255, 255, 255));
        lblBarcode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblBarcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(153, 153, 153));
        lblDate.setText("Issued Date: ");

        lblDate1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblDate1.setForeground(new java.awt.Color(153, 153, 153));
        lblDate1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate1.setText("+94 766 80 1659");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(lblDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblDate1))
                .addGap(15, 15, 15))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
